### ISSUE TITLE
No void return value support

### ISSUE THREAD

**Issue by vit9696** [d0c-s4vage/pfp#27]
This fails to execute in pfp though works fine in 010 Editor. The issue is in return keyword which seems to require a value.

```
void func() {
#ifndef DEBUG
    return;
#endif
    Printf("Hello\n");
}
func();
```

**Comment by d0c-s4vage** [comment]
Backtrace:

```
Traceback (most recent call last):
  File "test_functions.py", line 144, in test_void_return
    """
  File "/home/james/__ws__/dev/pfp/tests/utils.py", line 70, in _test_parse_build
    dom = pfp.parse(data, template, debug=debug, predefines=predefines)
  File "../pfp/__init__.py", line 85, in parse
    keep_successful = keep_successful
  File "../pfp/interp.py", line 672, in parse
    res = self._run(keep_successful)
  File "../pfp/interp.py", line 865, in _run
    traceback
  File "/home/james/__ws__/dev/pfp/tests/py3venv/lib/python3.4/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "../pfp/interp.py", line 844, in _run
    res = self._handle_node(self._ast, None, None, self._stream)
  File "../pfp/interp.py", line 937, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "../pfp/interp.py", line 960, in _handle_file_ast
    self._handle_node(child, scope, ctxt, stream)
  File "../pfp/interp.py", line 937, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "../pfp/interp.py", line 1891, in _handle_func_call
    return func.call(func_args, ctxt, scope, stream, self, node.coord)
  File "../pfp/functions.py", line 46, in call
    interp._handle_node(self.body, self._scope, ctxt, stream)
  File "../pfp/interp.py", line 937, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "../pfp/interp.py", line 1924, in _handle_compound
    self._handle_node(child, scope, ctxt, stream)
  File "../pfp/interp.py", line 937, in _handle_node
    res = self._node_switch[node.__class__](node, scope, ctxt, stream)
  File "../pfp/interp.py", line 1943, in _handle_return
    ret_val = self._handle_node(node.expr, scope, ctxt, stream)
  File "../pfp/interp.py", line 913, in _handle_node
    self._coord = node.coord
pfp.errors.PfpError: AttributeError: 'NoneType' object has no attribute 'coord'
```
