### ISSUE TITLE
some error when parsing PNG file 

### ISSUE THREAD

**Issue by rootkiter** [d0c-s4vage/pfp#96]
pfp --keep -t PNG.bt ~/Desktop/Snip20191209_8.png
Traceback (most recent call last):
  File "/usr/local/bin/pfp", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/pfp/__main__.py", line 55, in main
    keep_successful=args.keep,
  File "/Library/Python/2.7/site-packages/pfp/__init__.py", line 91, in parse
    printf=printf,
  File "/Library/Python/2.7/site-packages/pfp/interp.py", line 733, in parse
    self._ast = self._parse_string(template, predefines)
  File "/Library/Python/2.7/site-packages/pfp/interp.py", line 878, in _parse_string
    keep_scopes=predefines,
  File "/Library/Python/2.7/site-packages/py010parser/__init__.py", line 137, in parse_string
    keep_scopes     = keep_scopes
  File "/Library/Python/2.7/site-packages/py010parser/c_parser.py", line 178, in parse
    debug=debuglevel)
  File "/Library/Python/2.7/site-packages/py010parser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/Library/Python/2.7/site-packages/py010parser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/Library/Python/2.7/site-packages/py010parser/c_parser.py", line 1957, in p_error
    column=self.clex.find_tok_column(p)))
  File "/Library/Python/2.7/site-packages/py010parser/plyparser.py", line 54, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
py010parser.plyparser.ParseError: /var/folders/dk/r4gfh4y12yg725hxq010rdjc0000gn/T/tmpd5gEpg:1:1: before: /

**Comment by d0c-s4vage** [comment]
Hrmm, thanks for reporting this! was it with the basic PNG template from 010?

**Comment by rootkiter** [comment]
Yes, I got it from the official website. . And the PNG file are as follows.
<img width="452" alt="test" src="https://user-images.githubusercontent.com/6734184/70881380-4f913e00-2007-11ea-8047-b8cb53740882.png">

**Comment by d0c-s4vage** [comment]
thanks for uploading the PNG!

**Comment by d0c-s4vage** [comment]
I got a different stack trace using the PNG template at https://www.sweetscape.com/010editor/repository/files/PNG.bt:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/james/__ws__/dev/pfp/pfp/__main__.py", line 61, in <module>
    main(sys.argv)
  File "/home/james/__ws__/dev/pfp/pfp/__main__.py", line 55, in main
    keep_successful=args.keep,
  File "/home/james/__ws__/dev/pfp/pfp/__init__.py", line 91, in parse
    printf=printf,
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 733, in parse
    self._ast = self._parse_string(template, predefines)
  File "/home/james/__ws__/dev/pfp/pfp/interp.py", line 878, in _parse_string
    keep_scopes=predefines,
  File "/home/james/__ws__/dev/pfp/venv3/lib/python3.6/site-packages/py010parser/__init__.py", line 137, in parse_string
    keep_scopes     = keep_scopes
  File "/home/james/__ws__/dev/pfp/venv3/lib/python3.6/site-packages/py010parser/c_parser.py", line 178, in parse
    debug=debuglevel)
  File "/home/james/__ws__/dev/pfp/venv3/lib/python3.6/site-packages/py010parser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/home/james/__ws__/dev/pfp/venv3/lib/python3.6/site-packages/py010parser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/home/james/__ws__/dev/pfp/venv3/lib/python3.6/site-packages/py010parser/c_parser.py", line 1957, in p_error
    column=self.clex.find_tok_column(p)))
  File "/home/james/__ws__/dev/pfp/venv3/lib/python3.6/site-packages/py010parser/plyparser.py", line 54, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
py010parser.plyparser.ParseError: /tmp/tmp1c4h6qfy:154:2: before: STRUCT_CALL
```

**Comment by rootkiter** [comment]
My environment:    MacOS + Python2.7
and `make install`

**Comment by d0c-s4vage** [comment]
If you pip install --upgrade pfp py010parser, you should be able to parse your PNG image now:

```
$> pfp -t PNG.bt error.png
struct {
    sig        = struct {
        btPngSignature = UShort[4]
    }
    chunk      = PNG_CHUNK[75]
        chunk[0] = struct {
                length     = UInt(13 [0000000d])
                type       = union {
                    ctype      = UInt(1229472850 [49484452])
                    cname      = Char[4] ('IHDR')
                }
                ihdr       = struct {
                    width      = UInt(904 [00000388])
                    height     = UInt(724 [000002d4])
                    bits       = UChar(8 [08])
                    color_type = Enum<Char>(6 [06])(AlphaTrueColor)
                    compr_method = Enum<Char>(0 [00])(Deflate)
                    filter_method = Enum<Char>(0 [00])(AdaptiveFiltering)
                    interlace_method = Enum<Char>(0 [00])(NoInterlace)
                }
                crc        = UInt(1233853686 [498b1cf6])
            }
        chunk[1] = struct {
                length     = UInt(3148 [00000c4c])
                type       = union {
                    ctype      = UInt(1766015824 [69434350])
                    cname      = Char[4] ('iCCP')
                }
                data       = UChar[3148] ('ICC Profile\x00\x00H\x89\x95W\x07\\\x93')
                crc        = UInt(3283273704 [c3b2c7e8])
            }
        chunk[2] = struct {
                length     = UInt(108 [0000006c])
                type       = union {
                    ctype      = UInt(1700284774 [65584966])
                    cname      = Char[4] ('eXIf')
                }
                data       = UChar[108] ('MM\x00*\x00\x00\x00\x08\x00\x04\x01\x1a\x00\x05\x00\x00\x00\x01\x00\x00')
                crc        = UInt(2926163853 [ae69b78d])
            }
        chunk[3] = struct {
                length     = UInt(9 [00000009])
                type       = union {
                    ctype      = UInt(1883789683 [70485973])
                    cname      = Char[4] ('pHYs')
                }
                phys       = struct {
                    physPixelPerUnitX = UInt(5669 [00001625])
                    physPixelPerUnitY = UInt(5669 [00001625])
                    physUnitSpec = Enum<Char>(1 [01])(Meter)
                }
                crc        = UInt(1230120176 [495224f0])
            }
        chunk[4] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('x\x01TýÝÎ$K\x96æ÷eîÌÜ_UÕÝÓ')
                crc        = UInt(2109225420 [7db839cc])
            }
        chunk[5] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('¬Ï³×ds|tr\x99ä$î-òüP¹\x1cð')
                crc        = UInt(3470212832 [ced73ee0])
            }
        chunk[6] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('ç¿\x0e*XD¾í\x7ff\x08ñC¿\x97±éè\x8bS')
                crc        = UInt(2489231562 [945ea8ca])
            }
        chunk[7] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ("êÛtÚ¿\x05'VÄ9¹Ñ\x9aMñê<!g'")
                crc        = UInt(3642384758 [d91a6176])
            }
        chunk[8] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x12À¸\x8f\x95Ä»U$dx£sðxÜí\t%\x08')
                crc        = UInt(3038131260 [b516343c])
            }
        chunk[9] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('ÊrWæc£\x11\tÖñgµ\x17íîn9\x8c×¤')
                crc        = UInt(2479628699 [93cc219b])
            }
        chunk[10] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ("2\x07?[\x9cu¢\x1eíÚÓÄ\x89Ï'\x19ì\x87x/")
                crc        = UInt(2516666175 [9601473f])
            }
        chunk[11] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('I0ñwÀ\x1bLRdç\x89\x19·À\x92&¿Â=;')
                crc        = UInt(3619470769 [d7bcbdb1])
            }
        chunk[12] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('ædT\x1cm²é\x83gR\x95-9="\x8cþ(W©')
                crc        = UInt(371795084 [1629248c])
            }
        chunk[13] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ("\x0c»\x9cýs_\x14©ôíkbÀõÈ¸'wóÊ")
                crc        = UInt(2310176232 [89b27de8])
            }
        chunk[14] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('üjbÉÎáJ\x16yÚ\x86\x9c°àö\x8fß\x7f\x0e\x83')
                crc        = UInt(1749768878 [684b5aae])
            }
        chunk[15] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('9\x90kümàÒçlà¬~WÊÂYÕì;\x1f')
                crc        = UInt(634199886 [25cd1f4e])
            }
        chunk[16] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('É\x81é{_ÐiaÃIµSß®8\x87a¾î\x00')
                crc        = UInt(4116180510 [f557ee1e])
            }
        chunk[17] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('Dÿ|}r\x9f\x00\x0f\x91`?7#\\ÜD;W·±')
                crc        = UInt(851329490 [32be41d2])
            }
        chunk[18] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('·Â\x16D\nYé ¶\x81(õ\\\x9em_ñpâÄ')
                crc        = UInt(3748075996 [df6719dc])
            }
        chunk[19] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('mq$;Úæ;¥3>j\x81ñÆ);\x913±Ú')
                crc        = UInt(1799473751 [6b41ca57])
            }
        chunk[20] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('La\x91É®÷ÑÉE³\x8b\x08\x83\x97\t\x00ß\x91çô')
                crc        = UInt(862430758 [3367a626])
            }
        chunk[21] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x9b\x11\x86ÌöùD¹v\x13ðH·rzòeùx\x91')
                crc        = UInt(3833907402 [e484c8ca])
            }
        chunk[22] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x7fâðWç\x0f®\ngê\x1d\\2¨ C4ù\x1b\x90')
                crc        = UInt(1215422215 [4871df07])
            }
        chunk[23] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('mÖIk¸DØ¹¦ü\x84Ùâ²c\x8fY\x9el\x01')
                crc        = UInt(172820963 [0a4d09e3])
            }
        chunk[24] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('ßZ\x044¸zlpÅ³«$\x9c&8\t2>¨¸')
                crc        = UInt(3558570680 [d41b7ab8])
            }
        chunk[25] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\t\x92\x99D\x1b§\x0fh2h·\x92 \x83Z\x07{rÃ\x1f')
                crc        = UInt(999372495 [3b9136cf])
            }
        chunk[26] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('¨\r\x8bÅ\x80ÙæÈD·\x03Z\\Î\x9d_Ù\x83nj')
                crc        = UInt(2623411481 [9c5e1519])
            }
        chunk[27] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('ýÅ\x04\x1fï\\}¼ø\x8e¾[ÅIvm\x91ß\x9c\x13')
                crc        = UInt(132285523 [07e28453])
            }
        chunk[28] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x13\x0fÆ®ª\x11R9×®\x8fÁ° UV\x9dÝÓc')
                crc        = UInt(2616679432 [9bf75c08])
            }
        chunk[29] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('ä°w èàð÷\x0eôù\x85\x7f\x94YÏ/Ê2n')
                crc        = UInt(3583264989 [d59448dd])
            }
        chunk[30] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('ë$s>:\x922\x8dð $\x1f\x92K\x00\x9c\x94Écp')
                crc        = UInt(1655128869 [62a74325])
            }
        chunk[31] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('b\x13ÄX°ùV#\x83áÇ\x8bÛ¬\x80}½\r6º')
                crc        = UInt(3279191884 [c3747f4c])
            }
        chunk[32] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x16CÞm¸¢Ó\x1f1ç?\x1a\x0e\x1dZ\x98\x19F\x9fe')
                crc        = UInt(4066474611 [f2617a73])
            }
        chunk[33] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('÷\x89\x9f}\x07½ô»Ø¬n\x83\x03±õqW\x85èÑ')
                crc        = UInt(9168716 [008be74c])
            }
        chunk[34] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ("'<»\x16Cà¡±%Ì8d-\x14ÿÝÍT¼é")
                crc        = UInt(3884037108 [e781b3f4])
            }
        chunk[35] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('k·óËU!\x90G[=rÕ_\x9fºv\x1aQÅ¶')
                crc        = UInt(1918901790 [72601e1e])
            }
        chunk[36] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('W@JÇk\x8b\x8dÅ\x03U\x8dõ¾ÝÏcÔgõS')
                crc        = UInt(407190971 [18453dbb])
            }
        chunk[37] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x0f\x01q\x0fW\x92Ü¸\x14@\x9c\x1a\x1b=ó\x8e\x85³5\x9c')
                crc        = UInt(700589646 [29c2264e])
            }
        chunk[38] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('M;\x87\x17_Éà(^¼Z+\x87\x88åÓ\x05,g»')
                crc        = UInt(81012080 [04d42570])
            }
        chunk[39] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('2\x00Õï*\x19¤ñ \x17\x9a\x89g3üoR\xad§¤')
                crc        = UInt(1416069867 [546782eb])
            }
        chunk[40] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('èu\x1aÝ»ø|\x02ë\x06Z\x9f{\x8fd\x8b-ïÞü')
                crc        = UInt(2199559138 [831a9be2])
            }
        chunk[41] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ("{¼î\x15Vèª\x98(Ì'ÏÀÌ\x91\x1b^\x97GÐ")
                crc        = UInt(3764096315 [e05b8d3b])
            }
        chunk[42] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('ß\x06\rºD\x9aÙj4\x08~T\x91\x1cí¸?\x8f\x9eÍ')
                crc        = UInt(442067797 [1a596b55])
            }
        chunk[43] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('Ç\x8a\x03\x8f~yvãA.\x14\n®[\x19#6\x99ÐE')
                crc        = UInt(2959074668 [b05fe56c])
            }
        chunk[44] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('½\x89&|aÏ\x08\x14\x94\x0cV©&\xa0=ý\x88?µÝ')
                crc        = UInt(2348755257 [8bff2939])
            }
        chunk[45] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x12i\x12Þ\x02¾\x8bK\x89vüÂ/á£:C"9è')
                crc        = UInt(2846401721 [a9a8a4b9])
            }
        chunk[46] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('©¥àìg38}O\x0cèæÛt\x11\x986\x13\x14`')
                crc        = UInt(1100471971 [4197dea3])
            }
        chunk[47] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x14sñâ}´çGÉ\x82$\x90\x8fþþgk\x0c\x93I')
                crc        = UInt(1356636012 [50dc9f6c])
            }
        chunk[48] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('ÌÅÊ4zÞx×wÏØíÐ&D\x93¿\x1a0Þ')
                crc        = UInt(2766434381 [a4e4704d])
            }
        chunk[49] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x03¯À¤\x18|ýÒµÖlN\x067Öø\x02oÔ\x06')
                crc        = UInt(2837357342 [a91ea31e])
            }
        chunk[50] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x05Yp ºYg×R[}\x8dÓöÙxð#Z>')
                crc        = UInt(1322122821 [4ecdfe45])
            }
        chunk[51] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x9cäiû_ð\x1bT*¼o¿\x10<î·\x98`:·')
                crc        = UInt(1902959260 [716cda9c])
            }
        chunk[52] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('¤Ø2^h-öÂ¾\x8aW./Å\nÀjý\x8d£')
                crc        = UInt(2457896397 [928085cd])
            }
        chunk[53] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('iO\x97\x05÷\x8b:µ¢ò\x0e927\x1f}þ\x08\x9f¸')
                crc        = UInt(727285815 [2b598037])
            }
        chunk[54] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('XO2È²¬\x1fbð\x19èúÄ\x90G\x19R¨Jà')
                crc        = UInt(1145980242 [444e4552])
            }
        chunk[55] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ("xH×2W)N\x06åQ\x19Ó'e·\x04õS \t")
                crc        = UInt(3361335835 [c859ea1b])
            }
        chunk[56] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('Ð\x19¦õÕìã\x1b\x01\x01\x9e¢/ðÌ)\t\x0f«µ')
                crc        = UInt(2847176227 [a9b47623])
            }
        chunk[57] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('QJW;Ù\x8fÃ\x0eðeâßðI¿\x9bY|\x94Ü')
                crc        = UInt(2970691290 [b11126da])
            }
        chunk[58] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('»p8{\x1a\x8ftsßÀgpP\x1aÝ?xûÊ3')
                crc        = UInt(2374784372 [8d8c5574])
            }
        chunk[59] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('û|\x17\x7f\x7fø¥±f\x07ß¼JWüûôØEk')
                crc        = UInt(2046901631 [7a013d7f])
            }
        chunk[60] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('çèxÿ¦Í½æ\x9bEû%üÒ{b®ñºv')
                crc        = UInt(2383477451 [8e10facb])
            }
        chunk[61] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\t²o¿i³©\x0bò\x90\x0c\x98\r\r&ðJ\x94n\x12')
                crc        = UInt(750212772 [2cb756a4])
            }
        chunk[62] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x86ÏcÝx<\x9e,ÊW\x9cÚ|1\x18ñÝ}ø;')
                crc        = UInt(3902353963 [e899322b])
            }
        chunk[63] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('o©.ø:\x9b76\xad-|\x16\x08_ä\x98¼Ð\x1b=')
                crc        = UInt(1880485519 [7015ee8f])
            }
        chunk[64] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ("G\x06'>u\x7füg©\x87J\x11ûyHR³§\x87Ï")
                crc        = UInt(141584318 [087067be])
            }
        chunk[65] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('~t\x0f>ÁÛIM\t@IÎËx\x9d\x0cÛ{âä')
                crc        = UInt(547125757 [209c79fd])
            }
        chunk[66] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x88Ì\x897à8\x98°ßq*\x87ÞñN\x16\x1d¤aÓ')
                crc        = UInt(1400273478 [53767a46])
            }
        chunk[67] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('ÿNþé·¿;ùíïþéä§¿w\x14K\x15I')
                crc        = UInt(2670775426 [9f30cc82])
            }
        chunk[68] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x877-\x0c\t\x8a\x13\x89çé\x0e¶ÉaÇfO7~+')
                crc        = UInt(2640771541 [9d66f9d5])
            }
        chunk[69] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('G8½\x8eGÉ¾£},aj 5\x14Þ\x82ó\x91\x8f')
                crc        = UInt(3195287437 [be74378d])
            }
        chunk[70] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('ÓjÓ\x99¯\x1f_ü½\x00«\r\x8d~øs»Å6Ë')
                crc        = UInt(2229872863 [84e928df])
            }
        chunk[71] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] (' _ð\x88mwÔ]£\x06\x10dç\x8f\x04»´Öþô')
                crc        = UInt(1388169060 [52bdc764])
            }
        chunk[72] = struct {
                length     = UInt(16384 [00004000])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[16384] ('\x05\x9dÕ×Ø¦çÐ\x11<÷ÜôI¸\x95¶\x8a>Ì')
                crc        = UInt(2298316505 [88fd86d9])
            }
        chunk[73] = struct {
                length     = UInt(5246 [0000147e])
                type       = union {
                    ctype      = UInt(1229209940 [49444154])
                    cname      = Char[4] ('IDAT')
                }
                data       = UChar[5246] ('hï§·Ü²q×lüÐn\x1a\x81Ðýñ\r_F')
                crc        = UInt(3713641965 [dd59aded])
            }
        chunk[74] = struct {
                length     = UInt(0 [00000000])
                type       = union {
                    ctype      = UInt(1229278788 [49454e44])
                    cname      = Char[4] ('IEND')
                }
                crc        = UInt(2923585666 [ae426082])
            }
}
```

```
$> pip freeze | grep -E "(pfp|py010parser)"
pfp==0.4.3
py010parser==0.1.18
```

**Comment by d0c-s4vage** [comment]
Needed to fix three bugs for this:

* d0c-s4vage/py010parser#31 - Failure parsing parameterized structs
* #98 - Tests and fixes to ensure we're handling parameterized, typedefd structs correctly in pfp (we weren't)
* d0c-s4vage/py010parser#33 - (introduced by d0c-s4vage/py010parser#31) - Error detecting if current statement is a typedef
